version: "3"
services:
  app:
    build: .
    init: true
    depends_on:
      - db
    restart: unless-stopped
    ports:
      - 5000:3001
    volumes:
      - .:/usr/src/app/

  db:
    image: mysql:latest
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: steplix
      MYSQL_USER: root
      MYSQL_PASSWORD: Ami16_Azu04%
      MYSQL_ROOT_PASSWORD: Ami16_Azu04%
    ports:
      - 3307:3306
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_NICE # CAP_SYS_NICE
    expose:
      - 3307
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:
